{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "Vw9yOkUNu-dB"
   },
   "outputs": [],
   "source": [
    "In [1]:\n",
    "from datetime import datetime\n",
    "Задание 1\n",
    "Печатные газеты использовали свой формат дат для каждого выпуска. Для каждой газеты из списка напишите формат указанной даты для перевода в объект datetime:\n",
    "The Moscow Times - Wednesday, October 2, 2002\n",
    "The Guardian - Friday, 11.10.13\n",
    "Daily News - Thursday, 18 August 1977\n",
    "\n",
    "In [2]:\n",
    "newspaper_name_1 = 'The Moscow Times'\n",
    "newspaper_name_2 = 'The Guardian'\n",
    "newspaper_name_3 = 'Daily News'\n",
    "\n",
    "newspaper_date_1 = 'Wednesday, October 2, 2002'\n",
    "newspaper_date_2 = 'Friday, 11.10.13'\n",
    "newspaper_date_3 = 'Thursday, 18 August 1977'\n",
    "\n",
    "datetime_1 = datetime.strptime(newspaper_date_1, '%A, %B %d, %Y')\n",
    "datetime_2 = datetime.strptime(newspaper_date_2, '%A, %d.%m.%y')\n",
    "datetime_3 = datetime.strptime(newspaper_date_3, '%A, %d %B %Y')\n",
    "\n",
    "print(f'{newspaper_name_1} - {datetime_1}')\n",
    "print(f'{newspaper_name_2} - {datetime_2}')\n",
    "print(f'{newspaper_name_3} - {datetime_3}')\n",
    "The Moscow Times - 2002-10-02 00:00:00\n",
    "The Guardian - 2013-10-11 00:00:00\n",
    "Daily News - 1977-08-18 00:00:00\n",
    "Задание 2\n",
    "Дан поток дат в формате YYYY-MM-DD, в которых встречаются некорректные значения: stream = [‘2018-04-02’, ‘2018-02-29’, ‘2018-19-02’]\n",
    "\n",
    "Напишите функцию, которая проверяет эти даты на корректность. Т. е. для каждой даты возвращает True (дата корректна) или False (некорректная дата).\n",
    "\n",
    "In [4]:\n",
    "stream = ['2018-04-02', '2018-02-29', '2018-19-02']\n",
    "\n",
    "for line in stream:\n",
    "    try:\n",
    "        line_date = datetime.strptime(line, '%Y-%m-%d')\n",
    "        print (f'{True} дата корректна.')\n",
    "    except:\n",
    "        print (f'{False} некорректная дата.')\n",
    "True дата корректна.\n",
    "False некорректная дата.\n",
    "False некорректная дата.\n",
    "Задание 3\n",
    "Напишите функцию date_range, которая возвращает список дат за период от start_date до end_date. Даты должны вводиться в формате YYYY-MM-DD. В случае неверного формата или при start_date > end_date должен возвращаться пустой список.\n",
    "\n",
    "In [19]:\n",
    "from datetime import timedelta\n",
    "In [28]:\n",
    "def date_range():\n",
    "    start_date = input('Введите дату в формате YYYY-MM-DD: ')\n",
    "    end_date = input('Введите дату в формате YYYY-MM-DD: ')\n",
    "    date_list = []\n",
    "    try:\n",
    "        start_date_dt = datetime.strptime(start_date, '%Y-%m-%d')\n",
    "        end_date_dt = datetime.strptime(end_date, '%Y-%m-%d')\n",
    "        if start_date <= end_date:\n",
    "            current_data = start_date_dt\n",
    "            while current_data <= end_date_dt:\n",
    "                date_list.append(current_data.strftime('%Y-%m-%d'))\n",
    "                current_data += timedelta(days=1)\n",
    "            print('Список дат:')\n",
    "            print('\\n'.join(date_list))\n",
    "        else:\n",
    "            print('Некорретный ввод. Список пуст.')\n",
    "            print(date_list)\n",
    "    except ValueError:\n",
    "            print('Некорретный ввод. Список пуст.')\n",
    "            print(date_list)\n",
    "In [29]:\n",
    "date_range()\n",
    "Введите дату в формате YYYY-MM-DD: 2021-04-01\n",
    "Введите дату в формате YYYY-MM-DD: 2021-04-19\n",
    "Список дат:\n",
    "2021-04-01\n",
    "2021-04-02\n",
    "2021-04-03\n",
    "2021-04-04\n",
    "2021-04-05\n",
    "2021-04-06\n",
    "2021-04-07\n",
    "2021-04-08\n",
    "2021-04-09\n",
    "2021-04-10\n",
    "2021-04-11\n",
    "2021-04-12\n",
    "2021-04-13\n",
    "2021-04-14\n",
    "2021-04-15\n",
    "2021-04-16\n",
    "2021-04-17\n",
    "2021-04-18\n",
    "2021-04-19\n",
    "In [30]:\n",
    "date_range()\n",
    "Введите дату в формате YYYY-MM-DD: 2021-04-01\n",
    "Введите дату в формате YYYY-MM-DD: 2021-01-01\n",
    "Некорретный ввод. Список пуст.\n",
    "[]\n",
    "In [31]:\n",
    "date_range()\n",
    "Введите дату в формате YYYY-MM-DD: 2009/12/1\n",
    "Введите дату в формате YYYY-MM-DD: 2021-04-1\n",
    "Некорретный ввод. Список пуст.\n",
    "[]\n",
    "In [32]:\n",
    "date_range()\n",
    "Введите дату в формате YYYY-MM-DD: 2021-02-01\n",
    "Введите дату в формате YYYY-MM-DD: 2021-02-29\n",
    "Некорретный ввод. Список пуст.\n",
    "[]\n",
    "Задание 4\n",
    "Ваш коллега прислал код функции:\n",
    "\n",
    "DEFAULT_USER_COUNT = 3\n",
    "\n",
    "def delete_and_return_last_user(region, default_list=[‘A100’, ‘A101’, ‘A102’]):\n",
    "\"\"“ Удаляет из списка default_list последнего пользователя\n",
    "и возвращает ID нового последнего пользователя.\n",
    "”\"\"\n",
    "element_to_delete = default_list[-1]\n",
    "default_list.remove(element_to_delete)\n",
    "\n",
    "return default_list[DEFAULT_USER_COUNT-2]\n",
    "При однократном вызове этой функции все работает корректно:\n",
    "delete_and_return_last_user(1)\n",
    "‘A101’\n",
    "\n",
    "Однако, при повторном вызове получается ошибка IndexError: list index out of range.\n",
    "\n",
    "Задание:\n",
    "\n",
    "Что значит ошибка list index out of range?\n",
    "Почему при первом запуске функция работает корректно, а при втором - нет?\n",
    "\n",
    "In [33]:\n",
    "DEFAULT_USER_COUNT = 3\n",
    "\n",
    "def delete_and_return_last_user(region, default_list=['A100', 'A101', 'A102']):\n",
    "    element_to_delete = default_list[-1]\n",
    "    default_list.remove(element_to_delete)\n",
    "    return default_list[DEFAULT_USER_COUNT-2]\n",
    "    \n",
    "delete_and_return_last_user(1)\n",
    "Out[33]:\n",
    "'A101'\n",
    "In [34]:\n",
    "delete_and_return_last_user(1)\n",
    "---------------------------------------------------------------------------\n",
    "IndexError                                Traceback (most recent call last)\n",
    "<ipython-input-34-bfb6c4f8c48e> in <module>\n",
    "----> 1 delete_and_return_last_user(1)\n",
    "\n",
    "<ipython-input-33-d150fcf924ef> in delete_and_return_last_user(region, default_list)\n",
    "      4     element_to_delete = default_list[-1]\n",
    "      5     default_list.remove(element_to_delete)\n",
    "----> 6     return default_list[DEFAULT_USER_COUNT-2]\n",
    "      7 \n",
    "      8 delete_and_return_last_user(1)\n",
    "\n",
    "IndexError: list index out of range\n",
    "Ответ:\n",
    "Что значит ошибка list index out of range?\n",
    "Потому, что при повторном обращении мы обращаемся к индексу элемента, которого уже нет в нашем списке. У нас изменился список, он сократился.\n",
    "Почему при первом запуске функция работает корректно, а при втором - нет?\n",
    "При первом обращении к функции - мы изменили список и скоратили его, у нас было три элементы и их индексы: 0, 1 и 2, на выходе мы получили список из двух элементов и соответственно два индекса 0 и 1. Если при повторном обращении к функции мы не изменим DEFAULT_USER_COUNT на верное количество элементов и не укажем верный индекс, то на выходе мы получим ошибку. После того как, мы обратились к функции в первый раз, список изменился: в списке остались два элемента с индексами 0 и 1."
   ]
  }
 ],
 "metadata": {
  "colab": {
   "authorship_tag": "ABX9TyMiPan6vIm64sCmOmPd4C0S",
   "name": "Исключения и обработка ошибок-предлекционный материал.ipynb",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
